export const siteConfig = {
  baseUrl: process.env.SITE_URL || "https://elderlywisdom.org",
  name: "Elderly Wisdom",
  shortName: "ElderlyWisdom",
  logo: "https://elderlywisdom.org/logo.svg",
  description: "ElderlyWisdom.org offers weekly articles, YouTube videos, and books created for adults 60 and over. Discover practical advice on family relationships, health, and purpose, plus a free 7-day family journal. Warm, uplifting wisdom for a joyful life after 60 — from author Solan Voss.",
  twitterHandle: "@SolanVoss",
  locale: "en_US",
  creator: "Solan Voss",
  sameAs: [
    "https://www.facebook.com/groups/1286296679591129",
    "https://www.youtube.com/@ElderlyWisdomMind",
    "https://pinterest.com/SolanVossPro",
    "https://x.com/SolanVoss",
    "https://www.amazon.de/stores/Solan-Voss/author/B0F8QWL2FP",
  ],

  fbLink: "https://www.facebook.com/groups/1286296679591129",
  youtubeLink: "https://www.youtube.com/@ElderlyWisdomMind?sub_confirmation=1",
  pinterestLink: "https://pinterest.com/SolanVossPro",
  xLink: "https://x.com/SolanVoss",
  amazonLink: "https://www.amazon.com/stores/Solan-Voss/author/B0F8QWL2FP",
  mailLink: "elderly.wisdom.daily@gmail.com",
  announcementBarLink: "https://www.youtube.com/watch?v=hQlN7JuAXb0&list=PLQ9BkpldciEn87uRFQYMSbj2hOBqqhh4C",
  youtubeChannelId: "UCCMW6U1RnJr8Gdv6lnB8aKA",
};
